PROC=hexrays_sample4
__CFLAGS=/wd4062 /wd4265
!include ..\plugin.mak

# MAKEDEP dependency list ------------------
$(F)hexrays_sample4$(O): $(I)area.hpp $(I)bytes.hpp $(I)fpro.h $(I)funcs.hpp       \
	          $(I)hexrays.hpp $(I)ida.hpp $(I)idp.hpp $(I)ieee.h        \
	          $(I)kernwin.hpp $(I)lines.hpp $(I)llong.hpp               \
	          $(I)loader.hpp $(I)nalt.hpp $(I)name.hpp $(I)netnode.hpp  \
	          $(I)pro.h $(I)segment.hpp $(I)typeinf.hpp $(I)ua.hpp      \
	          $(I)xref.hpp hexrays_sample4.cpp
