
; ZProtect SDK for MASM/POASM/Tasm
; by forgot 2k8

Code_Confusion_START              equ     <db      0EBh,008h,053h,054h,05Fh,053h,054h,041h,052h,054h>
Code_Confusion_END                equ     <db      0EBh,008h,053h,054h,05Fh,053h,054h,045h,04Eh,044h>

ZProtect_VM_START              equ     <db      0EBh,008h,056h,04Dh,05Fh,053h,054h,041h,052h,054h>
ZProtect_VM_END                equ     <db      0EBh,008h,056h,04Dh,05Fh,056h,04Dh,045h,04Eh,044h>
