[General]
SyntaxVersion=2
BeginHotkey=122
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=2f87ff29-19cc-404b-836e-7d9b6ccf8ac4
Description=按下热键，访问脚本仓库，上千脚本任您下载
Enable=0
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
//访问按键精灵官网提供的源码库，学习脚本制作技巧
Call RunApp("http://www.vrbrothers.com/cn/qmacro/qcodelib/Browse/Index")
